name: todo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Cupertino
  cupertino_icons: ^1.0.6
    #Easy date time
  easy_date_timeline: ^1.1.3
    #Slidable
  flutter_slidable: ^3.1.1
  #Provider
  provider: ^6.1.2
  #Google fonts
  google_fonts: ^6.2.1
  # local Notification
  flutter_local_notifications: ^17.2.2
    #Localization
  flutter_localization: ^0.2.1
  # For change between localization
  intl: ^0.19.0
  #Firebase core 
  firebase_core: ^3.3.0
  # Clould Firestore for saving data in datebase
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # Add this line to enable localization code generation

  assets:
    - assets/images/
