name: todo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_date_timeline: ^1.1.3
  flutter_slidable: ^3.1.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.2
  flutter_localization: ^0.2.1
  intl: ^0.19.0
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # Add this line to enable localization code generation

  assets:
    - assets/images/
