// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY367y7aHgRZUAtxPSi7ReRi3xjvwhATE',
    appId: '1:226588439503:web:011ad5d368769f64dbd8ba',
    messagingSenderId: '226588439503',
    projectId: 'todo-app-76541',
    authDomain: 'todo-app-76541.firebaseapp.com',
    storageBucket: 'todo-app-76541.appspot.com',
    measurementId: 'G-5MG3XSW7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8bAEvmMe4sRM1Wm9BM9sJbBaXCEYo8M',
    appId: '1:226588439503:android:fa3b9c7ab83f8651dbd8ba',
    messagingSenderId: '226588439503',
    projectId: 'todo-app-76541',
    storageBucket: 'todo-app-76541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTbAJvRC3tLl6B3y8ShrqJu7eGWNowRkw',
    appId: '1:226588439503:ios:5ac8a9002be0672adbd8ba',
    messagingSenderId: '226588439503',
    projectId: 'todo-app-76541',
    storageBucket: 'todo-app-76541.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTbAJvRC3tLl6B3y8ShrqJu7eGWNowRkw',
    appId: '1:226588439503:ios:5ac8a9002be0672adbd8ba',
    messagingSenderId: '226588439503',
    projectId: 'todo-app-76541',
    storageBucket: 'todo-app-76541.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY367y7aHgRZUAtxPSi7ReRi3xjvwhATE',
    appId: '1:226588439503:web:b7aab37b4769aeffdbd8ba',
    messagingSenderId: '226588439503',
    projectId: 'todo-app-76541',
    authDomain: 'todo-app-76541.firebaseapp.com',
    storageBucket: 'todo-app-76541.appspot.com',
    measurementId: 'G-1FEFNRD7KT',
  );
}
